
export const LuisArceTwitter = require('./@LuchoXBolivia.json')
export const CarlosMesaTwitter = require('./@carlosdmesag.json')
export const LuisFCamachoTwitter = require('./@LuisFerCamachoV.json')
export const ChiHyunChungTwitter = require('./@ChiHyunChung1.json')
// export const FelicianoMamaniTwitter = require('./@Feliciano-Mamani.json')
// export const MariaBayaTwitter = require('./@MariaCruzBaya.json')
export const JorgeQuirogaTwitter = require('./@tutoquiroga.json')
export const MASTwitter = require('./@BOmereceMAS.json')
export const CCTwitter = require('./@ComunidadCBo.json')
// export const CreemosTwitter = require('./@CreemosBolivia.json')
// export const FPVTwitter = require('./@Frente-Para-la-Victoria-FPV.json')
// export const PanBolTwitter = require('./@PartidodeAccionNacionalBolivian0.json')
// export const Libre21Twitter = require('./@Libre-21.json')
