
export const LuisArceFacebook = require('./@LuchoXBolivia.json')
export const CarlosMesaFacebook = require('./@carlosdmesag.json')
export const LuisFCamachoFacebook = require('./@LFCamachoVaca.json')
export const ChiHyunChungFacebook = require('./@ChiHyunChungOficial.json')
export const FelicianoMamaniFacebook = require('./@Feliciano-Mamani.json')
export const MariaBayaFacebook = require('./@MariaCruzBaya.json')
export const JorgeQuirogaFacebook = require('./@TutoQuiroga.json')
export const MASFacebook = require('./@boliviamerecemas.json')
// export const CCFacebook = require('./@GobiernoDeCiudadanos.json')
export const CreemosFacebook = require('./@CreemosBolivia.json')
export const FPVFacebook = require('./@Frente-Para-la-Victoria-FPV.json')
export const PanBolFacebook = require('./@PartidodeAccionNacionalBolivian0.json')
export const Libre21Facebook = require('./@Libre-21.json')
