
// export const LuisArceYoutube = require('./@LuchoXBolivia.json')
export const CarlosMesaYoutube = require('./Carlos Mesa.json')
// export const LuisFCamachoYoutube = require('./@LuisFerCamachoV.json')
// export const ChiHyunChungYoutube = require('./@ChiHyunChung1.json')
// export const FelicianoMamaniYoutube = require('./@Feliciano-Mamani.json')
// export const MariaBayaYoutube = require('./@MariaCruzBaya.json')
export const JorgeQuirogaYoutube = require('./Tuto Quiroga.json')
// export const MASYoutube = require('./@BOmereceMAS.json')
// export const CCYoutube = require('./@ComunidadCBo.json')
// export const CreemosYoutube = require('./@CreemosBolivia.json')
// export const FPVYoutube = require('./@Frente-Para-la-Victoria-FPV.json')
// export const PanBolYoutube = require('./@PartidodeAccionNacionalBolivian0.json')
// export const Libre21Youtube = require('./@Libre-21.json')
